
Instrument.create(name:'trumpet')
Instrument.create(name:'tuba')
Instrument.create(name:'double bass')
Instrument.create(name:'guitar')
Instrument.create(name:'bass guitar')
Instrument.create(name:'singing')
Instrument.create(name:'rapping')
Instrument.create(name:'synth')
Instrument.create(name:'drumset')

Genre.create(name: 'Hip Hop')
Genre.create(name: 'Country')
Genre.create(name: 'Flamenco')
Genre.create(name: 'Classic Rock')
Genre.create(name: 'Punk Rock')
Genre.create(name: 'Indie')
Genre.create(name: 'R&B')
Genre.create(name: 'Carnatic')
Genre.create(name: 'Classical')
Genre.create(name: 'Reggae')
Genre.create(name: 'Calypso')
Genre.create(name: 'Funk')
Genre.create(name: 'House music')
Genre.create(name: 'Tango')


Location.create(name: 'London')
Location.create(name: 'NYC')
Location.create(name: 'Boston')
Location.create(name: 'London')
Location.create(name: 'Atlanta')
Location.create(name: 'Houston')
Location.create(name: 'Los Angeles')
Location.create(name: 'Mexico City')
Location.create(name: 'Venice')
Location.create(name: 'Mumbai')
Location.create(name: 'Oslo')

10.times do 
  user = User.create(name: Faker::Name.name, password:'1234', picture_url: Faker::Twitter.user[:profile_image_url_https],email_address: Faker::Internet.email,genre_id:Genre.random.id,instrument_id:Instrument.random.id,location_id: Location.random.id)
  user.update(looking_for_id: Instrument.random.id)
end 

User.create(name:'admin',password:'password',picture_url:"password",email_address:"test",genre:Genre.first,instrument:Instrument.first,location:Location.first,looking_for:Instrument.second)
